import Head from 'next/head'
import BooksList from '../components/BooksList'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Book Store Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <BooksList/>
    </div>
  )
}
